### Pre-Processing Data before feeding into Dashboard

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Demand_USEP_2015_to_2019.csv')
df["TRADING_DATE"] = pd.to_datetime(df["TRADING_DATE"])

In [3]:
df.head()

  TRADING_DATE  PERIOD    DEMAND   USEP
0   2015-01-01       1  4498.580  90.46
1   2015-01-01       2  4452.310  89.45
2   2015-01-01       3  4409.886  89.24
3   2015-01-01       4  4373.470  88.88
4   2015-01-01       5  4334.386  84.84

In [4]:
# Creating column for period time (for the 48 periods)
list_of_periods = ['00:00','00:30','01:00','01:30','02:00','02:30','03:00','03:30',
                   '04:00','04:30','05:00','05:30','06:00','06:30','07:00','07:30',
                   '08:00','08:30','09:00','09:30','10:00','10:30','11:00','11:30',
                   '12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30',
                   '16:00','16:30','17:00','17:30','18:00','18:30','19:00','19:30',
                   '20:00','20:30','21:00','21:30','22:00','22:30','23:00','23:30'           
                  ]

In [5]:
df['PERIOD_TIME'] = np.tile(list_of_periods, len(df)//len(list_of_periods) + 1)[:len(df)]

In [6]:
df.head(48)

   TRADING_DATE  PERIOD    DEMAND    USEP PERIOD_TIME
0    2015-01-01       1  4498.580   90.46       00:00
1    2015-01-01       2  4452.310   89.45       00:30
2    2015-01-01       3  4409.886   89.24       01:00
3    2015-01-01       4  4373.470   88.88       01:30
4    2015-01-01       5  4334.386   84.84       02:00
5    2015-01-01       6  4274.687   79.12       02:30
6    2015-01-01       7  4222.164   76.99       03:00
7    2015-01-01       8  4187.433   76.06       03:30
8    2015-01-01       9  4159.184   75.63       04:00
9    2015-01-01      10  4149.150   75.54       04:30
10   2015-01-01      11  4153.404   75.54       05:00
11   2015-01-01      12  4185.768   75.57       05:30
12   2015-01-01      13  4235.881   76.07       06:00
13   2015-01-01      14  4268.280   77.00       06:30
14   2015-01-01      15  4269.752   77.01       07:00
15   2015-01-01      16  4340.743   79.32       07:30
16   2015-01-01      17  4464.849   89.24       08:00
17   2015-01-01      18  4582.459   96.21       08:30
18   2015-01-01      19  4666.894  120.68       09:00
19   2015-01-01      20  4741.852  133.05       09:30
20   2015-01-01      21  4805.299   80.94       10:00
21   2015-01-01      22  4884.695   89.10       10:30
22   2015-01-01      23  4907.547   89.36       11:00
23   2015-01-01      24  4883.189   85.03       11:30
24   2015-01-01      25  4870.003   85.54       12:00
25   2015-01-01      26  4871.092   85.54       12:30
26   2015-01-01      27  4871.822   85.52       13:00
27   2015-01-01      28  4885.872   89.09       13:30
28   2015-01-01      29  4888.422   89.36       14:00
29   2015-01-01      30  4889.366   89.09       14:30
30   2015-01-01      31  4893.675   93.82       15:00
31   2015-01-01      32  4893.646   93.82       15:30
32   2015-01-01      33  4863.363   90.28       16:00
33   2015-01-01      34  4842.718   89.58       16:30
34   2015-01-01      35  4853.239   90.37       17:00
35   2015-01-01      36  4868.279  201.04       17:30
36   2015-01-01      37  4907.323  211.98       18:00
37   2015-01-01      38  5001.395  142.35       18:30
38   2015-01-01      39  5088.281  164.51       19:00
39   2015-01-01      40  5106.148  202.34       19:30
40   2015-01-01      41  5118.215  202.98       20:00
41   2015-01-01      42  5124.259  203.36       20:30
42   2015-01-01      43  5082.252  201.20       21:00
43   2015-01-01      44  4953.624  142.38       21:30
44   2015-01-01      45  4815.830  101.87       22:00
45   2015-01-01      46  4712.504   89.38       22:30
46   2015-01-01      47  4621.444  172.09       23:00
47   2015-01-01      48  4546.933  172.07       23:30

In [7]:
df.to_csv('df_2.csv',index=False)

In [8]:
# Creating monthly forecast df 
df['MMYYYY'] = pd.to_datetime(df['TRADING_DATE']).dt.to_period('M')
df_monthly = pd.DataFrame(df.groupby('MMYYYY')['USEP'].mean())

In [9]:
df_monthly.reset_index(drop=False,inplace=True)

In [10]:
df_monthly.head()

    MMYYYY        USEP
0  2015-01   90.624321
1  2015-02   93.290454
2  2015-03   81.722117
3  2015-04   98.095049
4  2015-05  103.183441

In [23]:
df_monthly['Type'] = 'Actual'
df_monthly['Type'][df_monthly.MMYYYY >= '2018-12'] = 'Projected'

C:\Users\klty0\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [26]:
df_monthly.tail(15)

     MMYYYY        USEP       Type
45  2018-10  154.023905     Actual
46  2018-11  114.212729     Actual
47  2018-12  100.440524  Projected
48  2019-01  112.571156  Projected
49  2019-02  115.168929  Projected
50  2019-03  113.537211  Projected
51  2019-04   99.623000  Projected
52  2019-05   93.276290  Projected
53  2019-06   89.842250  Projected
54  2019-07  112.716512  Projected
55  2019-08   93.277910  Projected
56  2019-09   95.967646  Projected
57  2019-10   94.392749  Projected
58  2019-11   88.794812  Projected
59  2019-12   71.238575  Projected

In [25]:
df_monthly.to_csv('df_monthly.csv')

### Trying out Periods selection

In [3]:
df = pd.read_csv('results_nov_dec.csv')
df["DATE"] = pd.to_datetime(df["DATE"])

In [4]:
scale_no = 0.8
scale_no = pd.to_numeric(scale_no)  # Convert scale value to number

selected_date = '9/12/2019'

In [5]:
# First filter by selected date.
# df_filtered is for original forecast, while df_modified is for modified graph
df_filtered = df[df["DATE"] == selected_date]
df_modified = df_filtered.copy()

In [6]:
periods = [1,2,3,4,5,6]

In [13]:
# Selecting periods to modify
df_modified_change = df_modified[df_modified['PERIOD'].isin(periods)]

In [14]:
df_modified_change

,DATE,PERIOD,DEMAND,USEP,TRADING_DATE_Year,TRADING_DATE_Month,TRADING_DATE_Week,TRADING_DATE_day,TRADING_DATE_day_name,USEP_wk_1,...,Advisory_fuel_change,Advisory_others,reg_wkdy_per_trnd,cont_wkdy_per_trnd,prim_wkdy_per_trnd,PeakDemand,ols_mod,decision,ensemble_1,ensemble_2
528,2019-09-12,1,5271.739,64.90,2019,12,50,0,Monday,62.14,...,0,0,0.018695,0.020669,0.022632,0,49.615737,52.64,51.127869,52.64
529,2019-09-12,2,5165.768,63.55,2019,12,50,0,Monday,60.45,...,0,0,0.016749,0.020207,0.022299,0,49.409671,52.64,51.024835,52.64
530,2019-09-12,3,5062.765,58.67,2019,12,50,0,Monday,57.46,...,0,0,0.015654,0.019976,0.021757,0,48.026068,48.60,48.313034,48.60
531,2019-09-12,4,4996.833,56.88,2019,12,50,0,Monday,56.26,...,0,0,0.015273,0.019855,0.021687,0,46.694261,48.60,47.647130,48.60
532,2019-09-12,5,4949.936,56.57,2019,12,50,0,Monday,55.14,...,0,0,0.015133,0.019607,0.021359,0,46.638911,46.67,46.654455,46.67
533,2019-09-12,6,4920.066,55.97,2019,12,50,0,Monday,53.98,...,0,0,0.015173,0.019524,0.021374,0,45.873703,46.67,46.271851,46.67

In [15]:
# Implement scaling factor for specific periods
df_modified_change['ensemble_1'] = df_modified_change['ensemble_1'].multiply(scale_no)

C:\Users\klty0\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
df_modified_change

,DATE,PERIOD,DEMAND,USEP,TRADING_DATE_Year,TRADING_DATE_Month,TRADING_DATE_Week,TRADING_DATE_day,TRADING_DATE_day_name,USEP_wk_1,...,Advisory_fuel_change,Advisory_others,reg_wkdy_per_trnd,cont_wkdy_per_trnd,prim_wkdy_per_trnd,PeakDemand,ols_mod,decision,ensemble_1,ensemble_2
528,2019-09-12,1,5271.739,64.90,2019,12,50,0,Monday,62.14,...,0,0,0.018695,0.020669,0.022632,0,49.615737,52.64,40.902295,52.64
529,2019-09-12,2,5165.768,63.55,2019,12,50,0,Monday,60.45,...,0,0,0.016749,0.020207,0.022299,0,49.409671,52.64,40.819868,52.64
530,2019-09-12,3,5062.765,58.67,2019,12,50,0,Monday,57.46,...,0,0,0.015654,0.019976,0.021757,0,48.026068,48.60,38.650427,48.60
531,2019-09-12,4,4996.833,56.88,2019,12,50,0,Monday,56.26,...,0,0,0.015273,0.019855,0.021687,0,46.694261,48.60,38.117704,48.60
532,2019-09-12,5,4949.936,56.57,2019,12,50,0,Monday,55.14,...,0,0,0.015133,0.019607,0.021359,0,46.638911,46.67,37.323564,46.67
533,2019-09-12,6,4920.066,55.97,2019,12,50,0,Monday,53.98,...,0,0,0.015173,0.019524,0.021374,0,45.873703,46.67,37.017481,46.67

In [18]:
df_modified_nochange = df_modified[~df_modified['PERIOD'].isin(periods)]

In [19]:
df_modified_nochange

,DATE,PERIOD,DEMAND,USEP,TRADING_DATE_Year,TRADING_DATE_Month,TRADING_DATE_Week,TRADING_DATE_day,TRADING_DATE_day_name,USEP_wk_1,...,Advisory_fuel_change,Advisory_others,reg_wkdy_per_trnd,cont_wkdy_per_trnd,prim_wkdy_per_trnd,PeakDemand,ols_mod,decision,ensemble_1,ensemble_2
534,2019-09-12,7,4895.425,55.13,2019,12,50,0,Monday,53.96,...,0,0,0.015140,0.019505,0.021266,0,45.098264,46.67,45.884132,46.670000
535,2019-09-12,8,4885.401,50.35,2019,12,50,0,Monday,50.36,...,0,0,0.014782,0.019336,0.021184,0,45.540029,45.25,45.395015,45.540029
536,2019-09-12,9,4882.324,48.51,2019,12,50,0,Monday,50.36,...,0,0,0.014445,0.019425,0.021193,0,44.894548,46.67,45.782274,46.670000
537,2019-09-12,10,4911.841,48.57,2019,12,50,0,Monday,53.95,...,0,0,0.014927,0.019283,0.021077,0,46.437227,45.27,45.853613,46.437227
538,2019-09-12,11,4995.014,55.13,2019,12,50,0,Monday,55.33,...,0,0,0.015692,0.019557,0.021414,0,46.940063,46.67,46.805031,46.940063
539,2019-09-12,12,5144.884,57.77,2019,12,50,0,Monday,57.45,...,0,0,0.017342,0.020003,0.021872,0,48.334819,48.60,48.467409,48.600000
540,2019-09-12,13,5340.076,64.58,2019,12,50,0,Monday,62.12,...,0,0,0.022110,0.020494,0.022350,0,50.613051,52.64,51.626526,52.640000
541,2019-09-12,14,5508.922,68.84,2019,12,50,0,Monday,62.66,...,0,0,0.022315,0.020611,0.022657,0,54.877331,52.64,53.758666,54.877331
542,2019-09-12,15,5710.947,64.80,2019,12,50,0,Monday,62.96,...,0,0,0.025012,0.020894,0.022350,1,58.848644,54.24,56.544322,58.848644
543,2019-09-12,16,5999.536,71.26,2019,12,50,0,Monday,74.08,...,0,0,0.025012,0.021165,0.021825,1,64.587961,68.27,66.428980,68.270000
544,2019-09-12,17,6275.738,75.52,2019,12,50,0,Monday,81.80,...,0,0,0.025012,0.021365,0.021252,1,71.011479,72.47,71.740740,72.470000
545,2019-09-12,18,6451.477,75.54,2019,12,50,0,Monday,83.00,...,0,0,0.025012,0.021427,0.020858,2,75.753865,77.71,76.731932,77.710000
546,2019-09-12,19,6567.159,80.00,2019,12,50,0,Monday,83.08,...,0,0,0.025012,0.021398,0.020081,2,78.833807,72.90,75.866904,78.833807
547,2019-09-12,20,6628.370,79.99,2019,12,50,0,Monday,83.61,...,0,0,0.023107,0.021445,0.019838,2,80.464442,72.59,76.527221,80.464442
548,2019-09-12,21,6683.447,84.20,2019,12,50,0,Monday,83.64,...,0,0,0.021828,0.021394,0.019623,2,82.211877,84.67,83.440938,84.670000
549,2019-09-12,22,6689.267,82.77,2019,12,50,0,Monday,83.97,...,0,0,0.021413,0.021252,0.019228,2,83.434517,84.67,84.052258,84.670000
550,2019-09-12,23,6661.544,81.06,2019,12,50,0,Monday,84.00,...,0,0,0.021487,0.021161,0.019164,2,83.734791,79.43,81.582395,83.734791
551,2019-09-12,24,6589.330,80.04,2019,12,50,0,Monday,83.45,...,0,0,0.020654,0.021167,0.019563,2,82.159660,72.59,77.374830,82.159660
552,2019-09-12,25,6527.350,76.17,2019,12,50,0,Monday,82.46,...,0,0,0.020954,0.021084,0.019453,2,81.407898,72.59,76.998949,81.407898
553,2019-09-12,26,6502.609,75.12,2019,12,50,0,Monday,83.65,...,0,0,0.021250,0.020994,0.019379,2,81.885967,72.59,77.237983,81.885967
554,2019-09-12,27,6544.784,75.12,2019,12,50,0,Monday,88.50,...,0,0,0.020263,0.021114,0.019382,2,82.647169,72.59,77.618584,82.647169
555,2019-09-12,28,6555.569,74.02,2019,12,50,0,Monday,93.14,...,0,0,0.020468,0.021140,0.019498,2,83.103735,79.43,81.266868,83.103735
556,2019-09-12,29,6554.282,68.56,2019,12,50,0,Monday,93.65,...,0,0,0.020943,0.021250,0.019900,2,82.495373,84.67,83.582687,84.670000
557,2019-09-12,30,6556.538,67.72,2019,12,50,0,Monday,89.00,...,0,0,0.020480,0.021239,0.019908,2,82.428943,79.43,80.929471,82.428943
558,2019-09-12,31,6584.912,68.64,2019,12,50,0,Monday,93.13,...,0,0,0.021006,0.021173,0.019845,2,83.064323,79.43,81.247161,83.064323
559,2019-09-12,32,6598.609,68.64,2019,12,50,0,Monday,84.85,...,0,0,0.020412,0.021192,0.019799,2,82.880927,79.43,81.155463,82.880927
560,2019-09-12,33,6576.384,68.63,2019,12,50,0,Monday,83.93,...,0,0,0.020931,0.021143,0.019442,2,82.941488,79.43,81.185744,82.941488
561,2019-09-12,34,6548.005,64.98,2019,12,50,0,Monday,81.85,...,0,0,0.023491,0.021083,0.019413,2,82.504609,72.59,77.547304,82.504609
562,2019-09-12,35,6456.487,64.98,2019,12,50,0,Monday,75.54,...,1,0,0.023275,0.021049,0.019488,2,80.742804,72.92,76.831402,80.742804
563,2019-09-12,36,6337.520,59.93,2019,12,50,0,Monday,75.53,...,1,0,0.025009,0.020925,0.019597,2,78.269945,72.61,75.439972,78.269945
564,2019-09-12,37,6278.517,63.85,2019,12,50,0,Monday,75.53,...,0,0,0.025012,0.020956,0.019938,2,76.386508,72.92,74.653254,76.386508
565,2019-09-12,38,6304.266,65.90,2019,12,50,0,Monday,76.53,...,0,0,0.025012,0.021060,0.020070,2,76.332276,72.92,74.626138,76.332276
566,2019-09-12,39,6332.123,69.97,2019,12,50,0,Monday,81.83,...,0,0,0.024600,0.021154,0.020229,2,76.179573,72.59,74.384786,76.179573
567,2019-09-12,40,6308.565,70.26,2019,12,50,0,Monday,86.55,...,0,0,0.023538,0.021313,0.020478,2,74.790395,75.95,75.370198,75.950000
568,2019-09-12,41,6269.764,69.02,2019,12,50,0,Monday,81.80,...,0,0,0.024249,0.021278,0.020777,2,74.038519,77.72,75.879260,77.720000
569,2019-09-12,42,6201.641,69.96,2019,12,50,0,Monday,74.25,...,0,0,0.022574,0.021369,0.021404,1,72.634930,77.70,75.167465,77.700000
570,2019-09-12,43,6122.518,67.82,2019,12,50,0,Monday,74.25,...,0,0,0.022529,0.021501,0.021523,1,70.196259,160.40,115.298129,160.400000
571,2019-09-12,44,5979.770,63.86,2019,12,50,0,Monday,83.73,...,0,0,0.022132,0.021582,0.022220,1,66.386066,76.73,71.558033,76.730000
572,2019-09-12,45,5800.631,58.17,2019,12,50,0,Monday,97.81,...,0,0,0.022135,0.021576,0.022620,1,62.394248,76.73,69.562124,76.730000
573,2019-09-12,46,5662.306,56.01,2019,12,50,0,Monday,78.95,...,0,0,0.021597,0.021529,0.022689,1,58.880187,67.72,63.300093,67.720000
574,2019-09-12,47,5508.400,49.03,2019,12,50,0,Monday,62.97,...,0,0,0.020812,0.021328,0.022293,1,53.258217,64.49,58.874109,64.490000
575,2019-09-12,48,5388.449,48.18,2019,12,50,0,Monday,60.56,...,0,0,0.020348,0.021249,0.022751,1,52.089614,64.49,58.289807,64.490000

In [21]:
df_modified_final = pd.concat([df_modified_change, df_modified_nochange], axis = 0)

In [22]:
df_modified_final

,DATE,PERIOD,DEMAND,USEP,TRADING_DATE_Year,TRADING_DATE_Month,TRADING_DATE_Week,TRADING_DATE_day,TRADING_DATE_day_name,USEP_wk_1,...,Advisory_fuel_change,Advisory_others,reg_wkdy_per_trnd,cont_wkdy_per_trnd,prim_wkdy_per_trnd,PeakDemand,ols_mod,decision,ensemble_1,ensemble_2
528,2019-09-12,1,5271.739,64.90,2019,12,50,0,Monday,62.14,...,0,0,0.018695,0.020669,0.022632,0,49.615737,52.64,40.902295,52.640000
529,2019-09-12,2,5165.768,63.55,2019,12,50,0,Monday,60.45,...,0,0,0.016749,0.020207,0.022299,0,49.409671,52.64,40.819868,52.640000
530,2019-09-12,3,5062.765,58.67,2019,12,50,0,Monday,57.46,...,0,0,0.015654,0.019976,0.021757,0,48.026068,48.60,38.650427,48.600000
531,2019-09-12,4,4996.833,56.88,2019,12,50,0,Monday,56.26,...,0,0,0.015273,0.019855,0.021687,0,46.694261,48.60,38.117704,48.600000
532,2019-09-12,5,4949.936,56.57,2019,12,50,0,Monday,55.14,...,0,0,0.015133,0.019607,0.021359,0,46.638911,46.67,37.323564,46.670000
533,2019-09-12,6,4920.066,55.97,2019,12,50,0,Monday,53.98,...,0,0,0.015173,0.019524,0.021374,0,45.873703,46.67,37.017481,46.670000
534,2019-09-12,7,4895.425,55.13,2019,12,50,0,Monday,53.96,...,0,0,0.015140,0.019505,0.021266,0,45.098264,46.67,45.884132,46.670000
535,2019-09-12,8,4885.401,50.35,2019,12,50,0,Monday,50.36,...,0,0,0.014782,0.019336,0.021184,0,45.540029,45.25,45.395015,45.540029
536,2019-09-12,9,4882.324,48.51,2019,12,50,0,Monday,50.36,...,0,0,0.014445,0.019425,0.021193,0,44.894548,46.67,45.782274,46.670000
537,2019-09-12,10,4911.841,48.57,2019,12,50,0,Monday,53.95,...,0,0,0.014927,0.019283,0.021077,0,46.437227,45.27,45.853613,46.437227
538,2019-09-12,11,4995.014,55.13,2019,12,50,0,Monday,55.33,...,0,0,0.015692,0.019557,0.021414,0,46.940063,46.67,46.805031,46.940063
539,2019-09-12,12,5144.884,57.77,2019,12,50,0,Monday,57.45,...,0,0,0.017342,0.020003,0.021872,0,48.334819,48.60,48.467409,48.600000
540,2019-09-12,13,5340.076,64.58,2019,12,50,0,Monday,62.12,...,0,0,0.022110,0.020494,0.022350,0,50.613051,52.64,51.626526,52.640000
541,2019-09-12,14,5508.922,68.84,2019,12,50,0,Monday,62.66,...,0,0,0.022315,0.020611,0.022657,0,54.877331,52.64,53.758666,54.877331
542,2019-09-12,15,5710.947,64.80,2019,12,50,0,Monday,62.96,...,0,0,0.025012,0.020894,0.022350,1,58.848644,54.24,56.544322,58.848644
543,2019-09-12,16,5999.536,71.26,2019,12,50,0,Monday,74.08,...,0,0,0.025012,0.021165,0.021825,1,64.587961,68.27,66.428980,68.270000
544,2019-09-12,17,6275.738,75.52,2019,12,50,0,Monday,81.80,...,0,0,0.025012,0.021365,0.021252,1,71.011479,72.47,71.740740,72.470000
545,2019-09-12,18,6451.477,75.54,2019,12,50,0,Monday,83.00,...,0,0,0.025012,0.021427,0.020858,2,75.753865,77.71,76.731932,77.710000
546,2019-09-12,19,6567.159,80.00,2019,12,50,0,Monday,83.08,...,0,0,0.025012,0.021398,0.020081,2,78.833807,72.90,75.866904,78.833807
547,2019-09-12,20,6628.370,79.99,2019,12,50,0,Monday,83.61,...,0,0,0.023107,0.021445,0.019838,2,80.464442,72.59,76.527221,80.464442
548,2019-09-12,21,6683.447,84.20,2019,12,50,0,Monday,83.64,...,0,0,0.021828,0.021394,0.019623,2,82.211877,84.67,83.440938,84.670000
549,2019-09-12,22,6689.267,82.77,2019,12,50,0,Monday,83.97,...,0,0,0.021413,0.021252,0.019228,2,83.434517,84.67,84.052258,84.670000
550,2019-09-12,23,6661.544,81.06,2019,12,50,0,Monday,84.00,...,0,0,0.021487,0.021161,0.019164,2,83.734791,79.43,81.582395,83.734791
551,2019-09-12,24,6589.330,80.04,2019,12,50,0,Monday,83.45,...,0,0,0.020654,0.021167,0.019563,2,82.159660,72.59,77.374830,82.159660
552,2019-09-12,25,6527.350,76.17,2019,12,50,0,Monday,82.46,...,0,0,0.020954,0.021084,0.019453,2,81.407898,72.59,76.998949,81.407898
553,2019-09-12,26,6502.609,75.12,2019,12,50,0,Monday,83.65,...,0,0,0.021250,0.020994,0.019379,2,81.885967,72.59,77.237983,81.885967
554,2019-09-12,27,6544.784,75.12,2019,12,50,0,Monday,88.50,...,0,0,0.020263,0.021114,0.019382,2,82.647169,72.59,77.618584,82.647169
555,2019-09-12,28,6555.569,74.02,2019,12,50,0,Monday,93.14,...,0,0,0.020468,0.021140,0.019498,2,83.103735,79.43,81.266868,83.103735
556,2019-09-12,29,6554.282,68.56,2019,12,50,0,Monday,93.65,...,0,0,0.020943,0.021250,0.019900,2,82.495373,84.67,83.582687,84.670000
557,2019-09-12,30,6556.538,67.72,2019,12,50,0,Monday,89.00,...,0,0,0.020480,0.021239,0.019908,2,82.428943,79.43,80.929471,82.428943
558,2019-09-12,31,6584.912,68.64,2019,12,50,0,Monday,93.13,...,0,0,0.021006,0.021173,0.019845,2,83.064323,79.43,81.247161,83.064323
559,2019-09-12,32,6598.609,68.64,2019,12,50,0,Monday,84.85,...,0,0,0.020412,0.021192,0.019799,2,82.880927,79.43,81.155463,82.880927
560,2019-09-12,33,6576.384,68.63,2019,12,50,0,Monday,83.93,...,0,0,0.020931,0.021143,0.019442,2,82.941488,79.43,81.185744,82.941488
561,2019-09-12,34,6548.005,64.98,2019,12,50,0,Monday,81.85,...,0,0,0.023491,0.021083,0.019413,2,82.504609,72.59,77.547304,82.504609
562,2019-09-12,35,6456.487,64.98,2019,12,50,0,Monday,75.54,...,1,0,0.023275,0.021049,0.019488,2,80.742804,72.92,76.831402,80.742804
563,2019-09-12,36,6337.520,59.93,2019,12,50,0,Monday,75.53,...,1,0,0.025009,0.020925,0.019597,2,78.269945,72.61,75.439972,78.269945
564,2019-09-12,37,6278.517,63.85,2019,12,50,0,Monday,75.53,...,0,0,0.025012,0.020956,0.019938,2,76.386508,72.92,74.653254,76.386508
565,2019-09-12,38,6304.266,65.90,2019,12,50,0,Monday,76.53,...,0,0,0.025012,0.021060,0.020070,2,76.332276,72.92,74.626138,76.332276
566,2019-09-12,39,6332.123,69.97,2019,12,50,0,Monday,81.83,...,0,0,0.024600,0.021154,0.020229,2,76.179573,72.59,74.384786,76.179573
567,2019-09-12,40,6308.565,70.26,2019,12,50,0,Monday,86.55,...,0,0,0.023538,0.021313,0.020478,2,74.790395,75.95,75.370198,75.950000
568,2019-09-12,41,6269.764,69.02,2019,12,50,0,Monday,81.80,...,0,0,0.024249,0.021278,0.020777,2,74.038519,77.72,75.879260,77.720000
569,2019-09-12,42,6201.641,69.96,2019,12,50,0,Monday,74.25,...,0,0,0.022574,0.021369,0.021404,1,72.634930,77.70,75.167465,77.700000
570,2019-09-12,43,6122.518,67.82,2019,12,50,0,Monday,74.25,...,0,0,0.022529,0.021501,0.021523,1,70.196259,160.40,115.298129,160.400000
571,2019-09-12,44,5979.770,63.86,2019,12,50,0,Monday,83.73,...,0,0,0.022132,0.021582,0.022220,1,66.386066,76.73,71.558033,76.730000
572,2019-09-12,45,5800.631,58.17,2019,12,50,0,Monday,97.81,...,0,0,0.022135,0.021576,0.022620,1,62.394248,76.73,69.562124,76.730000
573,2019-09-12,46,5662.306,56.01,2019,12,50,0,Monday,78.95,...,0,0,0.021597,0.021529,0.022689,1,58.880187,67.72,63.300093,67.720000
574,2019-09-12,47,5508.400,49.03,2019,12,50,0,Monday,62.97,...,0,0,0.020812,0.021328,0.022293,1,53.258217,64.49,58.874109,64.490000
575,2019-09-12,48,5388.449,48.18,2019,12,50,0,Monday,60.56,...,0,0,0.020348,0.021249,0.022751,1,52.089614,64.49,58.289807,64.490000

### Testing out inputs for speech bubble in dashboard

In [29]:
df = pd.read_csv('results_nov_dec.csv')
df["DATE"] = pd.to_datetime(df["DATE"])

In [30]:
fake_today = '13/12/2019'
df_today = df[df['DATE'] == fake_today]

In [32]:
row_usep_max = df_today.loc[df_today['USEP'].idxmax()]
row_usep_min = df_today.loc[df_today['USEP'].idxmin()]

today_usep_max = row_usep_max['USEP']
today_usep_min = row_usep_min['USEP']

today_usep_max_period = row_usep_max['PERIOD']
today_usep_min_period = row_usep_min['PERIOD']

In [36]:
today_usep_min

54.1

In [39]:
from datetime import date
today = date.today()

In [41]:
import calendar
day_of_week = calendar.day_name[today.weekday()]

In [42]:
day_of_week

'Tuesday'

In [45]:
from datetime import datetime as dt
hour = dt.now().hour

### Get temperatures from OpenWeatherMap

In [48]:
import json, requests

In [49]:
complete_url = "http://api.openweathermap.org/data/2.5/forecast?q=Singapore&APPID=563e076e56d92629d40c15952da749b6"

# get method of requests module
# return response object
response = requests.get(complete_url)
x = response.json()

In [53]:
x['list'][1]['main']['temp']

304.5

### Get temperatures from NEA

In [54]:
import json, requests
from datetime import datetime as dt

In [56]:
date.today()

datetime.date(2020, 4, 1)

In [59]:
today_for_weather = date.today()
today_for_weather = today_for_weather.strftime("%Y-%m-%d")
today_for_weather

'2020-04-01'

In [60]:
complete_url = f"https://api.data.gov.sg/v1/environment/24-hour-weather-forecast?date={today_for_weather}"

# get method of requests module
# return response object
response = requests.get(complete_url)
x = response.json()

In [64]:
x

{'items': [{'update_timestamp': '2020-04-01T05:51:18+08:00',
   'timestamp': '2020-04-01T05:33:00+08:00',
   'valid_period': {'start': '2020-04-01T06:00:00+08:00',
    'end': '2020-04-02T06:00:00+08:00'},
   'general': {'forecast': 'Showers',
    'relative_humidity': {'low': 55, 'high': 90},
    'temperature': {'low': 24, 'high': 35},
    'wind': {'speed': {'low': 5, 'high': 15}, 'direction': 'NNE'}},
   'periods': [{'time': {'start': '2020-04-01T06:00:00+08:00',
      'end': '2020-04-01T12:00:00+08:00'},
     'regions': {'west': 'Fair (Day)',
      'east': 'Fair (Day)',
      'central': 'Fair (Day)',
      'south': 'Fair (Day)',
      'north': 'Fair (Day)'}},
    {'time': {'start': '2020-04-01T12:00:00+08:00',
      'end': '2020-04-01T18:00:00+08:00'},
     'regions': {'west': 'Showers',
      'east': 'Fair (Day)',
      'central': 'Fair (Day)',
      'south': 'Fair (Day)',
      'north': 'Showers'}},
    {'time': {'start': '2020-04-01T18:00:00+08:00',
      'end': '2020-04-02T06:00:00+08:00'},
     'regions': {'west': 'Partly Cloudy (Night)',
      'east': 'Partly Cloudy (Night)',
      'central': 'Partly Cloudy (Night)',
      'south': 'Partly Cloudy (Night)',
      'north': 'Partly Cloudy (Night)'}}]},
  {'update_timestamp': '2020-04-01T12:06:19+08:00',
   'timestamp': '2020-04-01T11:47:00+08:00',
   'valid_period': {'start': '2020-04-01T12:00:00+08:00',
    'end': '2020-04-02T12:00:00+08:00'},
   'general': {'forecast': 'Showers',
    'relative_humidity': {'low': 55, 'high': 90},
    'temperature': {'low': 24, 'high': 35},
    'wind': {'speed': {'low': 5, 'high': 15}, 'direction': 'NNE'}},
   'periods': [{'time': {'start': '2020-04-01T12:00:00+08:00',
      'end': '2020-04-01T18:00:00+08:00'},
     'regions': {'west': 'Showers',
      'east': 'Fair (Day)',
      'central': 'Fair (Day)',
      'south': 'Fair (Day)',
      'north': 'Showers'}},
    {'time': {'start': '2020-04-01T18:00:00+08:00',
      'end': '2020-04-02T06:00:00+08:00'},
     'regions': {'west': 'Partly Cloudy (Night)',
      'east': 'Partly Cloudy (Night)',
      'central': 'Partly Cloudy (Night)',
      'south': 'Partly Cloudy (Night)',
      'north': 'Partly Cloudy (Night)'}},
    {'time': {'start': '2020-04-02T06:00:00+08:00',
      'end': '2020-04-02T12:00:00+08:00'},
     'regions': {'west': 'Partly Cloudy (Day)',
      'east': 'Partly Cloudy (Day)',
      'central': 'Partly Cloudy (Day)',
      'south': 'Partly Cloudy (Day)',
      'north': 'Partly Cloudy (Day)'}}]}],
 'api_info': {'status': 'healthy'}}

In [75]:
min_temp = x['items'][0]['general']['temperature']['low']
max_temp = x['items'][0]['general']['temperature']['high']
condition = x['items'][0]['general']['forecast']

In [79]:
condition = x['items'][0]['general']['forecast']
condition

'Showers'

In [83]:
chr(176)

'°'

### DateTime Format Testing

In [12]:
df = pd.read_csv('results_nov_dec.csv')

In [13]:
df.dtypes

DATE                                 object
PERIOD                                int64
DEMAND                              float64
USEP                                float64
TRADING_DATE_Year                     int64
TRADING_DATE_Month                    int64
TRADING_DATE_Week                     int64
TRADING_DATE_day                      int64
TRADING_DATE_day_name                object
USEP_wk_1                           float64
wkdy_per_trnd                       float64
wk_per_trnd                         float64
temp_mean                           float64
temp_min                            float64
temp_max                            float64
month_USEP                          float64
Elect_Gtrends                         int64
Elect_Gtrends_1                       int64
holiday                               int64
Advisory_forced_outage                int64
Advisory_outage_without_approval      int64
Advisory_emergency_operating          int64
Advisory_high_risk                    int64
Advisory_fuel_change                  int64
Advisory_others                       int64
reg_wkdy_per_trnd                   float64
cont_wkdy_per_trnd                  float64
prim_wkdy_per_trnd                  float64
PeakDemand                            int64
ols_mod                             float64
decision                            float64
ensemble_1                          float64
ensemble_2                          float64
dtype: object

In [14]:
df['DATE'] = pd.to_datetime(df['DATE'],infer_datetime_format = True)

In [16]:
df['DATE']

0     2019-08-11
1     2019-08-11
2     2019-08-11
3     2019-08-11
4     2019-08-11
         ...
763   2019-12-13
764   2019-12-13
765   2019-12-13
766   2019-12-13
767   2019-12-13
Name: DATE, Length: 768, dtype: datetime64[ns]

In [18]:
df2 = pd.read_csv('results_nov_dec.csv')

In [19]:
df2['DATE'] = pd.to_datetime(df['DATE'], format = '%d/%m/%Y')

In [22]:
df2['DATE'].sample(15)

33    2019-08-11
27    2019-08-11
349   2019-11-15
378   2019-11-15
563   2019-09-12
381   2019-11-15
472   2019-07-12
388   2019-06-12
454   2019-07-12
598   2019-10-12
415   2019-06-12
528   2019-09-12
649   2019-11-12
573   2019-09-12
173   2019-11-11
Name: DATE, dtype: datetime64[ns]

In [23]:
print(df2['DATE'])

0     2019-08-11
1     2019-08-11
2     2019-08-11
3     2019-08-11
4     2019-08-11
         ...
763   2019-12-13
764   2019-12-13
765   2019-12-13
766   2019-12-13
767   2019-12-13
Name: DATE, Length: 768, dtype: datetime64[ns]

In [27]:
from datetime import datetime as dt
date = '2019-12-13'
date = dt.strptime(date.split(' ')[0], '%Y-%m-%d')

In [28]:
date

datetime.datetime(2019, 12, 13, 0, 0)

In [31]:
dt.strptime('2019-12-13'.split(' ')[0], '%Y-%m-%d')

datetime.datetime(2019, 12, 13, 0, 0)

#### Doing Multiple Groupbys

In [3]:
df = pd.read_csv('Demand_USEP_2015_to_2019.csv')
df["TRADING_DATE"] = pd.to_datetime(df["TRADING_DATE"], dayfirst=True)

In [ ]:
df2 = df.groupby